apiVersion: v1
kind: ConfigMap
metadata:
  name: eks-saga-trail
  namespace: eks-saga
data:
  TZ: "timeZone"
  PORT: "8080"
  REGION: "regionId"
  DBHOST: "dbEndpoint"
  DBPORT: "3306"
  DBUSER: "pod_user"
  DBNAME: "saga"
